nodejs-buildpack/nodejs_buildpack-cflinuxfs4-v1.8.42.zip:
  size: 6081389
  object_id: f42b1881-edf4-4ad4-7374-fc357068388e
  sha: sha256:a002a504f3388e19adfd0d7e5c2d690c0831489ae734a50547096a1308832454
