nodejs-buildpack/nodejs_buildpack-cflinuxfs4-v1.8.44.zip:
  size: 5988948
  object_id: 0a804c49-82b7-463f-5e89-b5881da24250
  sha: sha256:57d4a1f3ca817933348501f58c63d09d0fa700c96c11ee6f17ee5e8021c14bb7
